[package]
name = "wei-ui"
version = "0.1.1"
edition = "2021"
description = "wei ui"
documentation = "https://github.com/zuiyue-com/wei-ui"
homepage = "https://github.com/zuiyue-com/wei-ui"
license = "MIT OR Apache-2.0"

[dependencies]
single-instance = "0.3"
wry = "0.32.0"