[package]
name = "wei-ui"
version = "0.1.0"
edition = "2021"
description = "wei ui"
documentation = "https://github.com/zuiyue-com/wei-ui"
homepage = "https://github.com/zuiyue-com/wei-ui"
license = "MIT OR Apache-2.0"

[dependencies]
